name: projeck1
description: "A new Flutter project."

publish_to: 'none' # Menandakan bahwa aplikasi ini tidak akan dipublikasikan ke pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.17.0 # Dependency untuk memformat tanggal dan waktu

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Bagian ini menambahkan gambar assets yang diperlukan oleh aplikasi
  assets:
    - assets/forest.png # Gambar latar belakang yang akan digunakan di aplikasi
